export default {
  apiRoot: "/api/v1",
  apiRootSecure: "/api/v1/secure",
  env: "",
  imageUrl: "/uploads/",
  currency: "€",
  defaultLocaleCurrencyCode: "en-IN",
  frenchLocaleCurrencyCode: "fr-FR",
  profileUrl: "/uploads/dp/",
  cohortlogoUrl: "/CohortProfile/Images/",
  logUrl: "/importationLogs/",
  issueLoggerCreateApi: "/api/v1/secure/issues/create",
  isMasterServer: false,
  isPublic: true,
  scannerUrl: "https://saintphilibertv3.mompartners.fr/scanner/#/",
  hospital_ext: "stp",
  appTitle: "SaintPhilibert",
  siteUrl: "https://saintphilibertv3.mompartners.fr/#",
  hospitalName: "MOM Hospital",
  aiChatRequired: true,
};
